# Generated by Django 2.2.2 on 2019-07-02 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190629_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
