# Generated by Django 2.2.2 on 2019-07-02 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('file', models.FilePathField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayinfoOrder',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('trade_no', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('is_type', models.SmallIntegerField(default=1)),
                ('status', models.SmallIntegerField(default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payinfo_buyer', to=settings.AUTH_USER_MODEL)),
                ('payinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payinfo_order', to='payinfo.PayInfo')),
            ],
        ),
    ]
