# Generated by Django 2.2.2 on 2019-07-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfo',
            name='file',
            field=models.URLField(),
        ),
    ]
